# Generated by Django 4.2.4 on 2023-09-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutBgImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_bg', models.ImageField(upload_to='about/bg/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutHeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_header_image', models.ImageField(upload_to='about/header/')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteBgImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_bg', models.ImageField(upload_to='quote/bg/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBgImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_bg', models.ImageField(upload_to='service/bg/')),
            ],
        ),
    ]
