# Generated by Django 4.2.4 on 2023-09-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutbgimage_aboutheaderimage_quotebgimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
