# Generated by Django 4.2.4 on 2023-09-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='banner title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='banner description')),
                ('banner_image', models.ImageField(upload_to='', verbose_name='banner image')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Carousel title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Carousel description')),
                ('carousel_image', models.ImageField(upload_to='', verbose_name='Carousel image')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='member name')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='member position')),
                ('email', models.EmailField(max_length=254, verbose_name='email adddress')),
                ('phone', models.CharField(max_length=50, verbose_name='mobile phone')),
                ('social_media_link1', models.URLField(blank=True, null=True, verbose_name='social media link 1')),
                ('social_media_link2', models.URLField(blank=True, null=True, verbose_name='social media link 2')),
                ('social_media_link3', models.URLField(blank=True, null=True, verbose_name='social media link 3')),
                ('social_media_link4', models.URLField(blank=True, null=True, verbose_name='social media link 4')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/images/', verbose_name='member image')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
