# Generated by Django 4.2.4 on 2024-07-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_banner_carousel_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_image',
            field=models.ImageField(upload_to='carousel/', verbose_name='Carousel image'),
        ),
    ]
