# Generated by Django 4.2.4 on 2023-09-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acceptance',
            field=models.BooleanField(default=False, verbose_name='acceptance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='accountance',
            field=models.BooleanField(default=False, verbose_name='accountance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='delivery_man',
            field=models.BooleanField(default=False, verbose_name='delivery man'),
        ),
        migrations.AlterField(
            model_name='user',
            name='importer',
            field=models.BooleanField(default=False, verbose_name='import'),
        ),
        migrations.AlterField(
            model_name='user',
            name='management',
            field=models.BooleanField(default=False, verbose_name='management'),
        ),
    ]
