# Generated by Django 4.2.4 on 2023-08-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masterparcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb', models.CharField(max_length=255)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_address', models.CharField(max_length=255)),
                ('sender_tel', models.CharField(max_length=255)),
                ('sender_city', models.CharField(max_length=255)),
                ('sender_country', models.CharField(max_length=255)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_address', models.CharField(max_length=255)),
                ('receiver_tel', models.CharField(max_length=255)),
                ('receiver_city', models.CharField(max_length=255)),
                ('receiver_country', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('freight', models.CharField(max_length=255)),
                ('insurance', models.CharField(max_length=255)),
                ('awb_pcs', models.CharField(max_length=255)),
                ('awb_kg', models.CharField(max_length=255)),
                ('arr_pcs', models.CharField(max_length=255)),
                ('arr_kg', models.CharField(max_length=255)),
                ('chargable_weight', models.CharField(max_length=255)),
                ('terms', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('expected_arrival_date', models.DateField()),
                ('date_received', models.DateField()),
                ('custom_value', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(choices=[('PP', 'pp'), ('cc', 'cc')], max_length=255)),
                ('dlv', models.CharField(max_length=255)),
                ('dlv_kg', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('width', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
            ],
        ),
    ]
