# Generated by Django 4.2.4 on 2023-08-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterparcel',
            name='order_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='masterparcel',
            name='chargable_weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='masterparcel',
            name='dlv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='masterparcel',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='masterparcel',
            name='length',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='masterparcel',
            name='terms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='masterparcel',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='masterparcel',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
