# Generated by Django 4.2.4 on 2023-08-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0002_masterparcel_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterparcel',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterparcel',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
