# Generated by Django 4.2.4 on 2023-08-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0004_subparcel_alter_masterparcel_arr_kg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterparcel',
            old_name='dlv',
            new_name='dlv_pcs',
        ),
        migrations.AddField(
            model_name='subparcel',
            name='arr_kg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='arr_pcs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='awb_kg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='awb_pcs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='chargable_weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='currency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='custom_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='dlv_kg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='dlv_pcs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='freight',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='insurance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='length',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='masterparcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sifex_system.masterparcel'),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='payment_mode',
            field=models.CharField(choices=[('PP', 'pp'), ('cc', 'cc')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='terms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
