# Generated by Django 4.2.4 on 2023-08-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0005_rename_dlv_masterparcel_dlv_pcs_subparcel_arr_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subparcel',
            name='awb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subparcel',
            name='order_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
