# Generated by Django 4.2.4 on 2023-08-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0007_substatus_masterstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterstatus',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='masterstatus',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterstatus',
            name='status',
            field=models.CharField(choices=[('MANIFATED', 'manifested'), ('RCS - recieved from shipper', 'RCS recieved from shipper'), ('OFFLOADED', 'offloaded'), ('DEPARTED', 'departed'), ('ON TRANSIT', 'on transit'), ('ARRIVED', 'arrived'), ('UNDER CLEARANCE', 'under clearance'), ('DELIVERED', 'derivered')], max_length=50, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='masterstatus',
            name='terminal',
            field=models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DAR - Dar es salaam', 'DAR - Dar es salaam'), ('DXB - Dubai', 'DXB - Dubai'), ('NBO - Nairobi', 'NBO - Nairobi'), ('SHJ - Sharjah', 'SHJ - Sharjah'), ('JNB - Johanesburg', 'JNB - Johanesburg'), ('MCT - Muscat', 'MCT - Muscat'), ('BOM - Mumbai', 'BOM - Mumbai'), ('ADD - Addis Ababa', 'ADD - Addis Ababa')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterstatus',
            name='time',
            field=models.TimeField(auto_now=True, null=True, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='substatus',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='substatus',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substatus',
            name='status',
            field=models.CharField(choices=[('MANIFATED', 'manifested'), ('RCS - recieved from shipper', 'RCS recieved from shipper'), ('OFFLOADED', 'offloaded'), ('DEPARTED', 'departed'), ('ON TRANSIT', 'on transit'), ('ARRIVED', 'arrived'), ('UNDER CLEARANCE', 'under clearance'), ('DELIVERED', 'derivered')], max_length=50, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='substatus',
            name='terminal',
            field=models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DAR - Dar es salaam', 'DAR - Dar es salaam'), ('DXB - Dubai', 'DXB - Dubai'), ('NBO - Nairobi', 'NBO - Nairobi'), ('SHJ - Sharjah', 'SHJ - Sharjah'), ('JNB - Johanesburg', 'JNB - Johanesburg'), ('MCT - Muscat', 'MCT - Muscat'), ('BOM - Mumbai', 'BOM - Mumbai'), ('ADD - Addis Ababa', 'ADD - Addis Ababa')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='substatus',
            name='time',
            field=models.TimeField(auto_now=True, null=True, verbose_name='Time'),
        ),
    ]
