# Generated by Django 4.2.4 on 2023-08-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0010_masterparcel_accepted_alter_masterstatus_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterstatus',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='substatus',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='status'),
        ),
    ]
