# Generated by Django 4.2.4 on 2023-08-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0011_alter_masterstatus_status_alter_substatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterparcel',
            name='arrived',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterparcel',
            name='delivered',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterparcel',
            name='departed',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterparcel',
            name='loaded',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterparcel',
            name='manifested',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterparcel',
            name='under_clearance',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
    ]
