# Generated by Django 4.2.4 on 2023-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0012_masterparcel_arrived_masterparcel_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterparcel',
            name='arrived',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterparcel',
            name='delivered',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterparcel',
            name='departed',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterparcel',
            name='loaded',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterparcel',
            name='manifested',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterparcel',
            name='under_clearance',
            field=models.BooleanField(default=False, max_length=255),
        ),
    ]
