# Generated by Django 4.2.4 on 2023-08-24 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0013_alter_masterparcel_arrived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slaveawb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_awb', models.CharField(max_length=255, null=True)),
                ('awb', models.CharField(max_length=255, null=True)),
                ('order_number', models.CharField(max_length=255, null=True)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('freight', models.CharField(max_length=255, null=True)),
                ('insurance', models.CharField(max_length=255, null=True)),
                ('awb_pcs', models.CharField(max_length=255, null=True)),
                ('awb_kg', models.CharField(max_length=255, null=True)),
                ('arr_pcs', models.CharField(blank=True, max_length=255, null=True)),
                ('arr_kg', models.CharField(blank=True, max_length=255, null=True)),
                ('chargable_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('terms', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(max_length=255, null=True)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('custom_value', models.CharField(max_length=255, null=True)),
                ('payment_mode', models.CharField(choices=[('PP', 'pp'), ('cc', 'cc')], max_length=255, null=True)),
                ('dlv_pcs', models.CharField(blank=True, max_length=255, null=True)),
                ('dlv_kg', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlaveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='status')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Date')),
                ('time', models.TimeField(auto_now=True, null=True, verbose_name='Time')),
                ('note', models.TextField(blank=True, null=True)),
                ('terminal', models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DAR - Dar es salaam', 'DAR - Dar es salaam'), ('DXB - Dubai', 'DXB - Dubai'), ('NBO - Nairobi', 'NBO - Nairobi'), ('SHJ - Sharjah', 'SHJ - Sharjah'), ('JNB - Johanesburg', 'JNB - Johanesburg'), ('MCT - Muscat', 'MCT - Muscat'), ('BOM - Mumbai', 'BOM - Mumbai'), ('ADD - Addis Ababa', 'ADD - Addis Ababa')], max_length=100, null=True)),
                ('sub_awb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slave_status', to='sifex_system.slaveawb')),
            ],
        ),
        migrations.RemoveField(
            model_name='substatus',
            name='sub_parcel',
        ),
        migrations.RenameModel(
            old_name='Masterparcel',
            new_name='Masterawb',
        ),
        migrations.DeleteModel(
            name='SubParcel',
        ),
        migrations.DeleteModel(
            name='SubStatus',
        ),
        migrations.AddField(
            model_name='slaveawb',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sifex_system.masterawb'),
        ),
    ]
