# Generated by Django 4.2.4 on 2023-09-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0015_masterawb_awb_type_slaveawb_awb_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterawb',
            name='awb_kg',
            field=models.FloatField(max_length=255),
        ),
    ]
