# Generated by Django 4.2.4 on 2023-09-06 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0019_masterawb_number_masterawb_number_of_parcel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaveawb',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slave_master_awb', to='sifex_system.masterawb'),
        ),
    ]
