# Generated by Django 4.2.4 on 2023-09-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0021_alter_slaveawb_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterawb',
            name='POD',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='masterawb',
            name='released',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='slaveawb',
            name='POD',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='slaveawb',
            name='released',
            field=models.BooleanField(default=False, max_length=255),
        ),
    ]
