# Generated by Django 4.2.4 on 2023-09-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0022_masterawb_pod_masterawb_released_slaveawb_pod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterstatus',
            name='delivered_to',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='delivered to'),
        ),
    ]
