# Generated by Django 4.2.4 on 2023-09-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0024_invoice_lineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='awb_kg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='chargable_weight',
            field=models.FloatField(null=True),
        ),
    ]
