# Generated by Django 4.2.4 on 2023-09-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0025_lineitem_awb_kg_lineitem_chargable_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sifex_system.masterawb'),
        ),
    ]
