# Generated by Django 4.2.4 on 2023-09-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0027_alter_lineitem_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='service',
            field=models.TextField(null=True),
        ),
    ]
