# Generated by Django 4.2.4 on 2023-09-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0028_alter_lineitem_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='message',
        ),
    ]
