# Generated by Django 4.2.4 on 2023-09-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0029_remove_invoice_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=120, null=True)),
                ('exchange_rate', models.FloatField(null=True)),
            ],
        ),
    ]
