# Generated by Django 4.2.4 on 2023-09-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0031_rename_total_amount_invoice_total_amount_tz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='amount',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='amount_tz',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
