# Generated by Django 4.2.4 on 2023-09-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0033_rename_total_amount_tz_invoice_total_amount_tzs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterawb',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='expected_arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
