# Generated by Django 4.2.4 on 2023-09-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0034_alter_masterawb_date_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterawb',
            name='awb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='awb_kg',
            field=models.FloatField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='awb_pcs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='currency',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='custom_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='desc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='freight',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='insurance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('PP', 'pp'), ('cc', 'cc')], max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='receiver_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='receiver_country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='receiver_tel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='sender_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='sender_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='sender_country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='sender_tel',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
