# Generated by Django 4.2.4 on 2023-09-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0035_alter_masterawb_awb_alter_masterawb_awb_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_phone',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
