# Generated by Django 4.2.4 on 2023-10-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0040_attendance_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='code_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
