# Generated by Django 4.2.4 on 2023-10-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0041_staff_code_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='in_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
