# Generated by Django 4.2.4 on 2023-10-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0042_alter_attendance_date_alter_attendance_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='out_time',
            field=models.TimeField(null=True),
        ),
    ]
