# Generated by Django 4.2.4 on 2024-07-13 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sifex_system', '0043_alter_attendance_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterawb',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='POD',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='arr_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='awb_kg',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='departed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='dlv_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='manifested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='parcel_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('PP', 'pp'), ('CC', 'cc')], max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='under_clearance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='POD',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='arr_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='awb_kg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='departed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='dlv_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='manifested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='payment_mode',
            field=models.CharField(choices=[('PP', 'pp'), ('CC', 'cc')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='under_clearance',
            field=models.BooleanField(default=False),
        ),
    ]
