# Generated by Django 4.2.4 on 2024-07-13 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sifex_system', '0044_masterawb_user_alter_invoice_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterstatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer_parcel_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slaveawb',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slave_issuers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slavestatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer_slave_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer_stafs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systempreference',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
