# Generated by Django 4.2.4 on 2024-07-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0045_customer_user_invoice_user_masterstatus_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterawb',
            name='account',
            field=models.BooleanField(default=False),
        ),
    ]
