# Generated by Django 4.2.4 on 2024-07-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0047_masterawb_receiver_company_masterawb_sender_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='awb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sifex_system.masterawb'),
        ),
    ]
