# Generated by Django 4.2.4 on 2024-07-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0048_invoice_awb'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterawb',
            name='invoice_paid',
            field=models.BooleanField(default=False),
        ),
    ]
