# Generated by Django 4.2.4 on 2024-07-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0049_masterawb_invoice_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='tracking_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
