# Generated by Django 4.2.4 on 2024-07-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0050_lineitem_tracking_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='origin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='awb_type',
            field=models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('shengzen awb', 'Shengzen awb')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='awb_type',
            field=models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('shengzen awb', 'Shengzen awb')], max_length=255, null=True),
        ),
    ]
