# Generated by Django 4.2.4 on 2024-07-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0051_invoice_origin_alter_masterawb_awb_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterawb',
            name='awb_type',
            field=models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DXB - Dubai', 'DXB - Dubai'), ('CAN - Express', 'CAN - Express'), ('MCO - Express', 'MCO - Express')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slaveawb',
            name='awb_type',
            field=models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DXB - Dubai', 'DXB - Dubai'), ('CAN - Express', 'CAN - Express'), ('MCO - Express', 'MCO - Express')], max_length=255, null=True),
        ),
    ]
