# Generated by Django 4.2.4 on 2024-07-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0052_alter_masterawb_awb_type_alter_slaveawb_awb_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterawb',
            old_name='account',
            new_name='bill',
        ),
    ]
