# Generated by Django 4.2.4 on 2024-07-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0053_rename_account_masterawb_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterawb',
            old_name='invoice_paid',
            new_name='billed',
        ),
    ]
