# Generated by Django 4.2.4 on 2024-07-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0054_rename_invoice_paid_masterawb_billed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
