# Generated by Django 4.2.4 on 2024-07-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0056_masterawb_invoice_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoces_line', to='sifex_system.invoice'),
        ),
    ]
