# Generated by Django 4.2.4 on 2024-07-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0057_alter_lineitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_detail',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
