# Generated by Django 4.2.4 on 2024-07-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0058_invoice_invoice_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterawb',
            name='bay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterawb',
            name='rack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
