# Generated by Django 4.2.4 on 2024-08-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0062_invoice_deleted_lineitem_deleted_masterawb_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterawb',
            name='payment_mode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
