# Generated by Django 4.2.4 on 2024-08-10 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sifex_system', '0063_alter_masterawb_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwbHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('master_awb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sifex_system.masterawb')),
            ],
        ),
    ]
