# Generated by Django 4.2.4 on 2024-08-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0065_awbremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='awbhistory',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AwbRemark',
        ),
    ]
