# Generated by Django 4.2.4 on 2024-08-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0068_freight'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='awb_type',
            field=models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DXB - Dubai', 'DXB - Dubai'), ('CAN - Express', 'CAN - Express'), ('MCO - Express', 'MCO - Express')], max_length=255, null=True),
        ),
    ]
