# Generated by Django 4.2.4 on 2024-08-13 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sifex_system', '0069_freight_awb_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('deleted', 'Deleted')], max_length=50)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sifex_system.freight')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
