# Generated by Django 4.2.4 on 2024-08-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0070_freighthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterstatus',
            name='terminal',
            field=models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DAR - Dar es salaam', 'DAR - Dar es salaam'), ('DXB - Dubai', 'DXB - Dubai'), ('NBO - Nairobi', 'NBO - Nairobi'), ('SHJ - Sharjah', 'SHJ - Sharjah'), ('JNB - Johanesburg', 'JNB - Johanesburg'), ('MCT - Muscat', 'MCT - Muscat'), ('BOM - Mumbai', 'BOM - Mumbai'), ('ADD - Addis Ababa', 'ADD - Addis Ababa'), ('ZNZ - Zanzibar', 'ZNZ - Zanzibar')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slavestatus',
            name='terminal',
            field=models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DAR - Dar es salaam', 'DAR - Dar es salaam'), ('DXB - Dubai', 'DXB - Dubai'), ('NBO - Nairobi', 'NBO - Nairobi'), ('SHJ - Sharjah', 'SHJ - Sharjah'), ('JNB - Johanesburg', 'JNB - Johanesburg'), ('MCT - Muscat', 'MCT - Muscat'), ('BOM - Mumbai', 'BOM - Mumbai'), ('ADD - Addis Ababa', 'ADD - Addis Ababa'), ('ZNZ - Zanzibar', 'ZNZ - Zanzibar')], max_length=100, null=True),
        ),
    ]
