# Generated by Django 4.2.4 on 2024-08-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0071_alter_masterstatus_terminal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterawb',
            name='freight_rate',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
