# Generated by Django 4.2.4 on 2024-08-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0072_masterawb_freight_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterawb',
            name='freight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='freight_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
