# Generated by Django 4.2.4 on 2024-08-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0073_alter_masterawb_freight_alter_masterawb_freight_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterawb',
            name='freight',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masterawb',
            name='freight_rate',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
