# Generated by Django 4.2.4 on 2024-08-17 11:07

from django.db import migrations


def clean_numeric_fields(apps, schema_editor):
    MasterAWB = apps.get_model('sifex_system', 'MasterAWB')

    for awb in MasterAWB.objects.all():
        if isinstance(awb.freight, str):
            awb.freight = awb.freight.replace('$', '').strip()
        if isinstance(awb.freight_rate, str):
            awb.freight_rate = awb.freight_rate.replace('$', '').strip()
        awb.save()



class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0074_alter_masterawb_freight_alter_masterawb_freight_rate'),
    ]

    operations = [
    ]
